ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS nf_numero text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS nf_serie text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS nf_chave text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS nf_status text NOT NULL DEFAULT 'sem_nf';