// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orqysvmrmyqebjntloac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycXlzdm1ybXlxZWJqbnRsb2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTk5ODIsImV4cCI6MjA4NjkzNTk4Mn0.-I32sj9guy2DyFeqi9woLtoRYZoF7AAB788pnWxYVbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});