// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usoezyigkgpnnvcvciwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzb2V6eWlna2dwbm52Y3ZjaXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMDkyMzcsImV4cCI6MjA4NjY4NTIzN30.HzZGcULb1FPhkux3hPVosFMd1kSwiqhGBaRwQqbbzao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});